// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'pref-enable'
  | 'pref-first-match-color'
  | 'pref-help'
  | 'pref-highlight-colors'
  | 'pref-input'
  | 'pref-other-match-color'
  | 'pref-title'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'preview-click-hint'
  | 'preview-click-to-jump'
  | 'preview-first-occurrence'
  | 'preview-variable'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
