// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "developerMode": boolean;
      "firstMatchColor": string;
      "firstMatchOpacity": number;
      "otherMatchColor": string;
      "otherMatchOpacity": number;
      "hoverFirstColor": string;
      "hoverFirstOpacity": number;
      "hoverOtherColor": string;
      "hoverOtherOpacity": number;
      "previewMaxWidth": number;
      "previewMaxHeight": number;
      "hoverDelayMs": number;
      "verticalFocusRatio": number;
    };
  }
}
